default:
  image: node:18-bullseye
  before_script:
  - yarn install --immutable

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
- test
- release

test:
  stage: test
  script:
  - yarn test

publish:
  stage: release
  script:
  - yarn run build
  - yarn run release
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: release
  script:
  - yarn run storybook:build
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
